### ISSUE TITLE
pyfastavalidator - pip cannot install 

### ISSUE THREAD

**Issue by nanzhen102** [linsalrob/py_fasta_validator#1]
Hi,

when I type `pip install pyfastavalidator`, it shows:
ERROR: Could not find a version that satisfies the requirement pyfastavalidator (from versions: none)
ERROR: No matching distribution found for pyfastavalidator

do you have any suggestions?

Thank you!

**Comment by linsalrob** [comment]
The command you need is

```
pip install py-fasta-validator
```

See the [pypi site for more information](https://pypi.org/project/py-fasta-validator/)

**Comment by linsalrob** [comment]
Sorry, the README was wrong. I am correcting

**Comment by nanzhen102** [comment]
Thank you!!
