### ISSUE TITLE
Error when run "make CFLAGS=-lpython3.8".

### ISSUE THREAD

**Issue by nanzhen102** [linsalrob/py_fasta_validator#2]
Hi Dr. Rob Edwards,

When I run `make`, or`make CFLAGS=-lpython3.8` or `make CFLAGS=-lpython3`, it shows `gcc  -Wall -std=c99 -Wall -o fasta_validate ./fasta_validate.c`. Do you have any suggestions regarding this error?

The python version is 3.8.19. 

The files are as follows:
drwxr-xr-x 8    4096 Jun 20 19:14 .git/
-rw-r--r-- 1    448 Jun 20 19:14 .gitignore
-rw-r--r-- 1    1068 Jun 20 19:14 LICENSE
-rw-r--r-- 1     297 Jun 20 19:14 Makefile
-rw-r--r-- 1    2506 Jun 20 19:14 README.md
-rwxr-xr-x 1   13088 Jun 20 19:20 fasta_validate*
-rw-r--r-- 1    4193 Jun 20 19:14 fasta_validate.c
-rw-r--r-- 1   809 Jun 20 19:14 fasta_validate.h
drwxr-xr-x 2   4096 Jun 20 19:14 test/
-rwxr-xr-x 1  1374 Jun 20 19:14 test.sh*

Thank you.
Best regards,

**Comment by linsalrob** [comment]
My guess is that you need to install `python3-dev`

Ubuntu:

```
sudo apt install python3-dev
```

CentOS:

```
dnf install python3-dev
```

To test the install and find the appropriate flags, you can use the `pkg-config` command:

do them separately to be clear what are `libs` and what are `cflags`:

```bash
pkg-config --cflags python3
pkg-config --libs python3
```

or do them together:

```bash
pkg-config --cflags --libs python
```

### NOTE: For python >= 3.8

You may need to use python3-embed instead of python3 to get the appropriate LIBS flag:

```bash
pkg-config --cflags --libs python3-embed
```

If your output from 

```bash
pkg-config --libs python3
``````

is empty, then please check `python3-embed`

You then need to use a `c++` compiler to compile it. Put the `cflags` and `libs` in the appropriate positions:

```bash
c++ -Wall -std=c99 -Wall -o fasta_validate -I/usr/include/python3.8 -I/usr/include/x86_64-linux-gnu/python3.8  ./fasta_validate.c -lpython3.8
```

**Comment by nanzhen102** [comment]
Thank you! I will have a try.

**Comment by linsalrob** [comment]
This worked for me:

```command-line
# create a virtual environment and activate it
virtualenv venv
source venv/bin/activate
# install py-fasta-validator
pip install py-fasta-validator
# clone the git repository
git clone https://github.com:linsalrob/py_fasta_validator.git
# run some tests
python py_fasta_validator/example_validations.py -f py_fasta_validator/test/good.fasta
python py_fasta_validator/example_validations.py -f py_fasta_validator/test/space.fasta
python py_fasta_validator/example_validations.py -f py_fasta_validator/test/no_first_line.fasta
python py_fasta_validator/example_validations.py -f py_fasta_validator/test/code.fasta
```

I will make an updated release soon with an easier interface, and also push to bioconda for a conda install.

**Comment by nanzhen102** [comment]
I used `conda create` to create env.

If I used `git clone https://github.com:linsalrob/py_fasta_validator.git`, it did work! I think I will use this method to analyze my fasta files.    :)

If I used `git clone https://github.com/linsalrob/fasta_validator.git`, I still got an error when I typed `make`.

I look forward to the updated release. Many thanks.

**Comment by linsalrob** [comment]
You can now install `py_fasta_validator` using conda:

```command-line
conda install -c bioconda py_fasta_validator
```

Let me know if that works for you

**Comment by nanzhen102** [comment]
It worked. Great!

Thank you :)
